[build]
  base = "frontend/"
  publish = "build/"
  command = "CI= npm run build"
  
[build.environment]
  NODE_VERSION = "14.17.0"
  NPM_VERSION = "7.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
